### ISSUE TITLE
iOS - buttons only load for the first card

### ISSUE THREAD

**Issue by Cinnamilk** [helq/pinyin-beginners-anki-deck#2]
The audio buttons for the sound -> pinyin cards for initials and finals only load for the first card shown, but not for others unless you return to the deck screen, edit screen, or any other similar screen. The buttons will load on the back of the card, just not the front. In addition, one audio file plays without prompting even though the deck options are set to not automatically play audio.

Tested on a 5th generation iPad on iOS 13.1.3

**Comment by helq** [comment]
Hi @Cinnamilk. Sorry for the reaally long delay on a response.

Unfortunately, I don't have the time to find out what the problem is. The code I wrote was meant to work only in Anki Desktop but it worked well in AnkiDroid and somebody reported it worked in iOS too. I don't intend to support in the long run iOS because I don't own a device with it. I'm sorry but it is too much of a hassle. If anybody finds a way to make it work in iOS I would love to get to know how.

Thank you for reaching out. I hope you find a solution :). Have a nice year
