### ISSUE TITLE
-uan -un -üan card bug

### ISSUE THREAD

**Issue by yisding** [helq/pinyin-beginners-anki-deck#8]
-üan zhuyin field should have ㄩㄢ but it has ㄨㄢ

When I try to edit the cards manually, Anki says:

"Sorry but this card cannot be displayed on this Anki client."

or

Front template has a problem:
Found '⁨{{#Compare with "Pinyin 3" multiple times (or once)? (create 3 cards or 1) [y=3cards]}}⁩', but there is no field called '⁨Compare with "Pinyin 3" multiple times (or once)? (create 3 cards or 1) [y=3cards]⁩'

Anki 2.1.49

**Comment by helq** [comment]
I think I found the source of the bug. The file which contains the respective zhuyin from pinyin is incomplete. "-üan", "lü", "nü" and "nüe" were missing from it.

So, to make sure I got it right: The zhuyin of "-üan" is ㄩㄢ, "lu" is ㄌㄨ, "lü" is ㄌㄩ, "lüe" is ㄌㄩㄝ, "nu" is ㄋㄨ, "nü" is ㄋㄩ and "nüe" is ㄋㄩㄝ.

Btw, the message "Sorry but this card cannot be displayed on this Anki client." is intentional. The preview functionality of Anki does not behave a 100% like the actual application.

Once I know that the zhuyin transcription (above) are correct, I'll update the deck in AnkiWeb. It'll take me more than a week though, as I am currently busy with other stuff, sorry. In the mean time, you can see the changes I made to the code in the commit b6167053910ee1daf5927942b1f7548069945b77. Follow the instructions to generate the deck. If that is too esoteric for you @yisding , you can make the change directly on the affected notes (like in the "-uan -un -üan"). You can't preview them, but they'll have the correct info.

Thanks a lot for reporting!

**Comment by yisding** [comment]
Yes, the Zhuyin are correct. Thank you! And thank you for the quick response.

So it looks like for a few cards, not just the preview is broken but it also doesn't work while studying. I loaded up the deck in a brand new account, and have attached a few screenshots. I originally thought it was an issue with this particular template, but it looks like it's not a template specific thing because some of the cards in the template work fine.

<img width="294" alt="Screen Shot 2022-01-14 at 1 27 37 PM" src="https://user-images.githubusercontent.com/1209314/149587750-0a1d86d1-5474-4ef9-afda-12c774f646f8.png">
<img width="727" alt="Screen Shot 2022-01-14 at 1 23 43 PM" src="https://user-images.githubusercontent.com/1209314/149587756-c2118b9a-211f-4fc7-9cc9-f31f7d830a75.png">

**Comment by helq** [comment]
Shoot, yeah, you are right. That's another bug. Go to "Browse", find a card in "(Minimal Pairs)" and press "Cards...". In there, the error appears in the following in card types 5, 6, 8 and 9.

I'll fix that later too. But for now, you can fix it by removing from the template the quotes (") that are around Pinyin 3 in the first line of the template and in the last. Notice, that you have to do this for the "Front template" and the "Back template" for all four card types.

I have no idea how long this bug has been lurking in there, sorry. It'll be fixed upstream "soon".

Thanks a lot for finding these annoying bugs! :D

**Comment by yisding** [comment]
OK, thank you! No, not at all. Thank you for the deck. It's been super helpful, and I'm glad you're able to find a fix for this.

**Comment by yisding** [comment]
<img width="430" alt="Screen Shot 2022-01-14 at 2 03 16 PM" src="https://user-images.githubusercontent.com/1209314/149591254-a31bd6c4-dea6-415e-bbfc-00a3f56195be.png">

Apologies. One more error while doing that!

**Comment by yisding** [comment]
OK I worked around the error by adding a few HTML comments in places. I needed to do it on 3 or 4 templates.

**Comment by helq** [comment]
Ok, I think I have finally fixed it. 8ed5aa8 should have fixed the "Card template X in notetype ... has a problem" message. Feel free to open another issue if there are still bugs around. Thank you for using the deck!
